{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os, sys\n",
    "from pathlib import Path"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# get all file .ipynb\n",
    "ipynb_files = list(Path('.').glob('*.ipynb'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "ipynb_files = sorted([str(f) for f in ipynb_files])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "ipynb_files = ipynb_files[:-1]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['1.APTM.ipynb',\n",
       " '2.IRRA.ipynb',\n",
       " '3.RaSa.ipynb',\n",
       " '4.PLIP.ipynb',\n",
       " '5.UniPT.ipynb',\n",
       " '6.LGUR.ipynb',\n",
       " '7.TBPS-CLIP.ipynb']"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ipynb_files"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[NbConvertApp] Converting notebook 1.APTM.ipynb to pdf\n",
      "/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/utils/pandoc.py:51: RuntimeWarning: You are using an unsupported version of pandoc (2.9.2.1).\n",
      "Your version must be at least (2.14.2) but less than (4.0.0).\n",
      "Refer to https://pandoc.org/installing.html.\n",
      "Continuing with doubts...\n",
      "  check_pandoc_version()\n",
      "[NbConvertApp] Support files will be in docs/1.APTM_files/\n",
      "[NbConvertApp] Making directory ./docs/1.APTM_files\n",
      "[NbConvertApp] Writing 81224 bytes to notebook.tex\n",
      "[NbConvertApp] Building PDF\n",
      "Traceback (most recent call last):\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/bin/jupyter-nbconvert\", line 8, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/jupyter_core/application.py\", line 280, in launch_instance\n",
      "    super().launch_instance(argv=argv, **kwargs)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 412, in start\n",
      "    self.convert_notebooks()\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 589, in convert_notebooks\n",
      "    self.convert_single_notebook(notebook_filename)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 555, in convert_single_notebook\n",
      "    output, resources = self.export_single_notebook(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 479, in export_single_notebook\n",
      "    output, resources = self.exporter.from_filename(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py\", line 386, in from_filename\n",
      "    return super().from_filename(filename, resources, **kw)  # type:ignore[return-value]\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/exporter.py\", line 201, in from_filename\n",
      "    return self.from_file(f, resources=resources, **kw)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py\", line 392, in from_file\n",
      "    return super().from_file(file_stream, resources, **kw)  # type:ignore[return-value]\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/exporter.py\", line 220, in from_file\n",
      "    return self.from_notebook_node(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 197, in from_notebook_node\n",
      "    self.run_latex(tex_file)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 166, in run_latex\n",
      "    return self.run_command(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 120, in run_command\n",
      "    raise OSError(msg)\n",
      "OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n",
      "[NbConvertApp] Converting notebook 2.IRRA.ipynb to pdf\n",
      "/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/utils/pandoc.py:51: RuntimeWarning: You are using an unsupported version of pandoc (2.9.2.1).\n",
      "Your version must be at least (2.14.2) but less than (4.0.0).\n",
      "Refer to https://pandoc.org/installing.html.\n",
      "Continuing with doubts...\n",
      "  check_pandoc_version()\n",
      "[NbConvertApp] Support files will be in docs/2.IRRA_files/\n",
      "[NbConvertApp] Making directory ./docs/2.IRRA_files\n",
      "[NbConvertApp] Writing 55015 bytes to notebook.tex\n",
      "[NbConvertApp] Building PDF\n",
      "Traceback (most recent call last):\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/bin/jupyter-nbconvert\", line 8, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/jupyter_core/application.py\", line 280, in launch_instance\n",
      "    super().launch_instance(argv=argv, **kwargs)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 412, in start\n",
      "    self.convert_notebooks()\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 589, in convert_notebooks\n",
      "    self.convert_single_notebook(notebook_filename)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 555, in convert_single_notebook\n",
      "    output, resources = self.export_single_notebook(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 479, in export_single_notebook\n",
      "    output, resources = self.exporter.from_filename(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py\", line 386, in from_filename\n",
      "    return super().from_filename(filename, resources, **kw)  # type:ignore[return-value]\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/exporter.py\", line 201, in from_filename\n",
      "    return self.from_file(f, resources=resources, **kw)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py\", line 392, in from_file\n",
      "    return super().from_file(file_stream, resources, **kw)  # type:ignore[return-value]\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/exporter.py\", line 220, in from_file\n",
      "    return self.from_notebook_node(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 197, in from_notebook_node\n",
      "    self.run_latex(tex_file)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 166, in run_latex\n",
      "    return self.run_command(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 120, in run_command\n",
      "    raise OSError(msg)\n",
      "OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n",
      "[NbConvertApp] Converting notebook 3.RaSa.ipynb to pdf\n",
      "/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/utils/pandoc.py:51: RuntimeWarning: You are using an unsupported version of pandoc (2.9.2.1).\n",
      "Your version must be at least (2.14.2) but less than (4.0.0).\n",
      "Refer to https://pandoc.org/installing.html.\n",
      "Continuing with doubts...\n",
      "  check_pandoc_version()\n",
      "[NbConvertApp] Support files will be in docs/3.RaSa_files/\n",
      "[NbConvertApp] Making directory ./docs/3.RaSa_files\n",
      "[NbConvertApp] Writing 45137 bytes to notebook.tex\n",
      "[NbConvertApp] Building PDF\n",
      "Traceback (most recent call last):\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/bin/jupyter-nbconvert\", line 8, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/jupyter_core/application.py\", line 280, in launch_instance\n",
      "    super().launch_instance(argv=argv, **kwargs)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 412, in start\n",
      "    self.convert_notebooks()\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 589, in convert_notebooks\n",
      "    self.convert_single_notebook(notebook_filename)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 555, in convert_single_notebook\n",
      "    output, resources = self.export_single_notebook(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 479, in export_single_notebook\n",
      "    output, resources = self.exporter.from_filename(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py\", line 386, in from_filename\n",
      "    return super().from_filename(filename, resources, **kw)  # type:ignore[return-value]\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/exporter.py\", line 201, in from_filename\n",
      "    return self.from_file(f, resources=resources, **kw)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py\", line 392, in from_file\n",
      "    return super().from_file(file_stream, resources, **kw)  # type:ignore[return-value]\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/exporter.py\", line 220, in from_file\n",
      "    return self.from_notebook_node(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 197, in from_notebook_node\n",
      "    self.run_latex(tex_file)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 166, in run_latex\n",
      "    return self.run_command(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 120, in run_command\n",
      "    raise OSError(msg)\n",
      "OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n",
      "[NbConvertApp] Converting notebook 4.PLIP.ipynb to pdf\n",
      "/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/utils/pandoc.py:51: RuntimeWarning: You are using an unsupported version of pandoc (2.9.2.1).\n",
      "Your version must be at least (2.14.2) but less than (4.0.0).\n",
      "Refer to https://pandoc.org/installing.html.\n",
      "Continuing with doubts...\n",
      "  check_pandoc_version()\n",
      "[NbConvertApp] Support files will be in docs/4.PLIP_files/\n",
      "[NbConvertApp] Making directory ./docs/4.PLIP_files\n",
      "[NbConvertApp] Writing 72614 bytes to notebook.tex\n",
      "[NbConvertApp] Building PDF\n",
      "Traceback (most recent call last):\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/bin/jupyter-nbconvert\", line 8, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/jupyter_core/application.py\", line 280, in launch_instance\n",
      "    super().launch_instance(argv=argv, **kwargs)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 412, in start\n",
      "    self.convert_notebooks()\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 589, in convert_notebooks\n",
      "    self.convert_single_notebook(notebook_filename)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 555, in convert_single_notebook\n",
      "    output, resources = self.export_single_notebook(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 479, in export_single_notebook\n",
      "    output, resources = self.exporter.from_filename(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py\", line 386, in from_filename\n",
      "    return super().from_filename(filename, resources, **kw)  # type:ignore[return-value]\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/exporter.py\", line 201, in from_filename\n",
      "    return self.from_file(f, resources=resources, **kw)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py\", line 392, in from_file\n",
      "    return super().from_file(file_stream, resources, **kw)  # type:ignore[return-value]\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/exporter.py\", line 220, in from_file\n",
      "    return self.from_notebook_node(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 197, in from_notebook_node\n",
      "    self.run_latex(tex_file)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 166, in run_latex\n",
      "    return self.run_command(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 120, in run_command\n",
      "    raise OSError(msg)\n",
      "OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n",
      "[NbConvertApp] Converting notebook 5.UniPT.ipynb to pdf\n",
      "/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/utils/pandoc.py:51: RuntimeWarning: You are using an unsupported version of pandoc (2.9.2.1).\n",
      "Your version must be at least (2.14.2) but less than (4.0.0).\n",
      "Refer to https://pandoc.org/installing.html.\n",
      "Continuing with doubts...\n",
      "  check_pandoc_version()\n",
      "[NbConvertApp] Support files will be in docs/5.UniPT_files/\n",
      "[NbConvertApp] Making directory ./docs/5.UniPT_files\n",
      "[NbConvertApp] Writing 30844 bytes to notebook.tex\n",
      "[NbConvertApp] Building PDF\n",
      "Traceback (most recent call last):\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/bin/jupyter-nbconvert\", line 8, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/jupyter_core/application.py\", line 280, in launch_instance\n",
      "    super().launch_instance(argv=argv, **kwargs)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 412, in start\n",
      "    self.convert_notebooks()\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 589, in convert_notebooks\n",
      "    self.convert_single_notebook(notebook_filename)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 555, in convert_single_notebook\n",
      "    output, resources = self.export_single_notebook(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 479, in export_single_notebook\n",
      "    output, resources = self.exporter.from_filename(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py\", line 386, in from_filename\n",
      "    return super().from_filename(filename, resources, **kw)  # type:ignore[return-value]\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/exporter.py\", line 201, in from_filename\n",
      "    return self.from_file(f, resources=resources, **kw)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py\", line 392, in from_file\n",
      "    return super().from_file(file_stream, resources, **kw)  # type:ignore[return-value]\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/exporter.py\", line 220, in from_file\n",
      "    return self.from_notebook_node(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 197, in from_notebook_node\n",
      "    self.run_latex(tex_file)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 166, in run_latex\n",
      "    return self.run_command(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 120, in run_command\n",
      "    raise OSError(msg)\n",
      "OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n",
      "[NbConvertApp] Converting notebook 6.LGUR.ipynb to pdf\n",
      "/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/utils/pandoc.py:51: RuntimeWarning: You are using an unsupported version of pandoc (2.9.2.1).\n",
      "Your version must be at least (2.14.2) but less than (4.0.0).\n",
      "Refer to https://pandoc.org/installing.html.\n",
      "Continuing with doubts...\n",
      "  check_pandoc_version()\n",
      "[NbConvertApp] Support files will be in docs/6.LGUR_files/\n",
      "[NbConvertApp] Making directory ./docs/6.LGUR_files\n",
      "[NbConvertApp] Writing 34306 bytes to notebook.tex\n",
      "[NbConvertApp] Building PDF\n",
      "Traceback (most recent call last):\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/bin/jupyter-nbconvert\", line 8, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/jupyter_core/application.py\", line 280, in launch_instance\n",
      "    super().launch_instance(argv=argv, **kwargs)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 412, in start\n",
      "    self.convert_notebooks()\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 589, in convert_notebooks\n",
      "    self.convert_single_notebook(notebook_filename)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 555, in convert_single_notebook\n",
      "    output, resources = self.export_single_notebook(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 479, in export_single_notebook\n",
      "    output, resources = self.exporter.from_filename(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py\", line 386, in from_filename\n",
      "    return super().from_filename(filename, resources, **kw)  # type:ignore[return-value]\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/exporter.py\", line 201, in from_filename\n",
      "    return self.from_file(f, resources=resources, **kw)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py\", line 392, in from_file\n",
      "    return super().from_file(file_stream, resources, **kw)  # type:ignore[return-value]\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/exporter.py\", line 220, in from_file\n",
      "    return self.from_notebook_node(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 197, in from_notebook_node\n",
      "    self.run_latex(tex_file)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 166, in run_latex\n",
      "    return self.run_command(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 120, in run_command\n",
      "    raise OSError(msg)\n",
      "OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n",
      "[NbConvertApp] Converting notebook 7.TBPS-CLIP.ipynb to pdf\n",
      "/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/utils/pandoc.py:51: RuntimeWarning: You are using an unsupported version of pandoc (2.9.2.1).\n",
      "Your version must be at least (2.14.2) but less than (4.0.0).\n",
      "Refer to https://pandoc.org/installing.html.\n",
      "Continuing with doubts...\n",
      "  check_pandoc_version()\n",
      "[NbConvertApp] Support files will be in docs/7.TBPS-CLIP_files/\n",
      "[NbConvertApp] Making directory ./docs/7.TBPS-CLIP_files\n",
      "[NbConvertApp] Writing 50148 bytes to notebook.tex\n",
      "[NbConvertApp] Building PDF\n",
      "Traceback (most recent call last):\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/bin/jupyter-nbconvert\", line 8, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/jupyter_core/application.py\", line 280, in launch_instance\n",
      "    super().launch_instance(argv=argv, **kwargs)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 412, in start\n",
      "    self.convert_notebooks()\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 589, in convert_notebooks\n",
      "    self.convert_single_notebook(notebook_filename)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 555, in convert_single_notebook\n",
      "    output, resources = self.export_single_notebook(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/nbconvertapp.py\", line 479, in export_single_notebook\n",
      "    output, resources = self.exporter.from_filename(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py\", line 386, in from_filename\n",
      "    return super().from_filename(filename, resources, **kw)  # type:ignore[return-value]\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/exporter.py\", line 201, in from_filename\n",
      "    return self.from_file(f, resources=resources, **kw)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py\", line 392, in from_file\n",
      "    return super().from_file(file_stream, resources, **kw)  # type:ignore[return-value]\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/exporter.py\", line 220, in from_file\n",
      "    return self.from_notebook_node(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 197, in from_notebook_node\n",
      "    self.run_latex(tex_file)\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 166, in run_latex\n",
      "    return self.run_command(\n",
      "  File \"/dscilab_dungvo/workspace/bin/envs/aptm/lib/python3.8/site-packages/nbconvert/exporters/pdf.py\", line 120, in run_command\n",
      "    raise OSError(msg)\n",
      "OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.\n"
     ]
    }
   ],
   "source": [
    "import jupyter\n",
    "for f in ipynb_files: \n",
    "    file_save = 'docs/' + f[:-6] + 'md'\n",
    "    print(file_save)\n",
    "    os.system('jupyter nbconvert --to markdown ' + f + ' --output ' + file_save)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "aptm",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.18"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
